/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import config.session;
import javax.swing.JOptionPane;
import testapp2.loginform;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SCC
 */
public class admindashboard extends javax.swing.JFrame {

    String nam;
    String ads;
    String uname;

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        initComponents();
    }
    Color navcolor = new Color(255,255,204);
         Color hovercolor = new Color(204,255,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        p_manage = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p_manage2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adminname = new javax.swing.JLabel();
        adminname1 = new javax.swing.JLabel();
        adminname2 = new javax.swing.JLabel();
        p_manage3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_manage4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p_manage5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(null);

        p_manage.setBackground(new java.awt.Color(204, 255, 255));
        p_manage.setForeground(new java.awt.Color(255, 255, 255));
        p_manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_manageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_manageMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-128.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Manage Scholarship");

        javax.swing.GroupLayout p_manageLayout = new javax.swing.GroupLayout(p_manage);
        p_manage.setLayout(p_manageLayout);
        p_manageLayout.setHorizontalGroup(
            p_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_manageLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10))
                .addGap(22, 22, 22))
        );
        p_manageLayout.setVerticalGroup(
            p_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(p_manage);
        p_manage.setBounds(180, 30, 170, 170);

        p_manage2.setBackground(new java.awt.Color(204, 255, 255));
        p_manage2.setForeground(new java.awt.Color(255, 255, 255));
        p_manage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manage2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_manage2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_manage2MouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-administrator-male-96.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Manage Students");

        javax.swing.GroupLayout p_manage2Layout = new javax.swing.GroupLayout(p_manage2);
        p_manage2.setLayout(p_manage2Layout);
        p_manage2Layout.setHorizontalGroup(
            p_manage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manage2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );
        p_manage2Layout.setVerticalGroup(
            p_manage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(p_manage2);
        p_manage2.setBounds(400, 30, 170, 170);

        adminname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adminname.setText("Admin");
        jPanel1.add(adminname);
        adminname.setBounds(30, 170, 120, 17);

        adminname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adminname1.setText("Admin");
        jPanel1.add(adminname1);
        adminname1.setBounds(30, 200, 120, 17);

        adminname2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adminname2.setText("Admin");
        jPanel1.add(adminname2);
        adminname2.setBounds(30, 140, 130, 20);

        p_manage3.setBackground(new java.awt.Color(204, 255, 255));
        p_manage3.setForeground(new java.awt.Color(255, 255, 255));
        p_manage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manage3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_manage3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_manage3MouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-medical-history-96.png"))); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Reports");

        javax.swing.GroupLayout p_manage3Layout = new javax.swing.GroupLayout(p_manage3);
        p_manage3.setLayout(p_manage3Layout);
        p_manage3Layout.setHorizontalGroup(
            p_manage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_manage3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(55, 55, 55))
            .addGroup(p_manage3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        p_manage3Layout.setVerticalGroup(
            p_manage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(p_manage3);
        p_manage3.setBounds(400, 230, 170, 170);

        p_manage4.setBackground(new java.awt.Color(204, 255, 255));
        p_manage4.setForeground(new java.awt.Color(255, 255, 255));
        p_manage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manage4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_manage4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_manage4MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-log-out-30.png"))); // NOI18N
        jLabel2.setText("LOG OUT");

        javax.swing.GroupLayout p_manage4Layout = new javax.swing.GroupLayout(p_manage4);
        p_manage4.setLayout(p_manage4Layout);
        p_manage4Layout.setHorizontalGroup(
            p_manage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_manage4Layout.setVerticalGroup(
            p_manage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(p_manage4);
        p_manage4.setBounds(580, 390, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("WELCOME!!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-education-100.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 0, 100, 100);

        p_manage5.setBackground(new java.awt.Color(204, 255, 255));
        p_manage5.setForeground(new java.awt.Color(255, 255, 255));
        p_manage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_manage5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_manage5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_manage5MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-medical-history-96.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Manage User");

        javax.swing.GroupLayout p_manage5Layout = new javax.swing.GroupLayout(p_manage5);
        p_manage5.setLayout(p_manage5Layout);
        p_manage5Layout.setHorizontalGroup(
            p_manage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(p_manage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        p_manage5Layout.setVerticalGroup(
            p_manage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_manage5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(p_manage5);
        p_manage5.setBounds(180, 230, 170, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scholarship.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 760, 440);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 120, 750, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uni.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 114);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       session sess= session.getInstance();
       if(sess.getUid()== 0){
           JOptionPane.showMessageDialog(null,"No account, Please login!");
           loginform lf=new loginform();
         lf.setVisible(true);
           this.dispose();
       }
       
       adminname.setText(""+sess.getFname());
       adminname1.setText(""+sess.getLname());
       adminname2.setText(""+sess.getEmail());
    }//GEN-LAST:event_formWindowActivated

    private void p_manage2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage2MouseExited
    p_manage2.setBackground(hovercolor);    
    }//GEN-LAST:event_p_manage2MouseExited

    private void p_manage2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage2MouseEntered
    p_manage2.setBackground(navcolor);    
    }//GEN-LAST:event_p_manage2MouseEntered

    private void p_manage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage2MouseClicked
       studentPage sp = null;
       sp = new studentPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_manage2MouseClicked

    private void p_manageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manageMouseExited
    p_manage.setBackground(hovercolor);    
    }//GEN-LAST:event_p_manageMouseExited

    private void p_manageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manageMouseEntered
    p_manage.setBackground(navcolor);      
    }//GEN-LAST:event_p_manageMouseEntered

    private void p_manage3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage3MouseEntered
       p_manage3.setBackground(hovercolor);  
    }//GEN-LAST:event_p_manage3MouseEntered

    private void p_manage3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage3MouseExited
      p_manage3.setBackground(navcolor);  
    }//GEN-LAST:event_p_manage3MouseExited

    private void p_manage4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage4MouseEntered
       p_manage4.setBackground(hovercolor);    
    }//GEN-LAST:event_p_manage4MouseEntered

    private void p_manage4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage4MouseExited
       p_manage4.setBackground(navcolor);    
    }//GEN-LAST:event_p_manage4MouseExited

    private void p_manage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage4MouseClicked
loginform lg = new loginform();
    lg.setVisible(true);
    this.dispose();       
    }//GEN-LAST:event_p_manage4MouseClicked

    private void p_manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manageMouseClicked
     scholarshippage usf = new scholarshippage();
        usf.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_p_manageMouseClicked

    private void p_manage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage3MouseClicked
      reports usf = new reports();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_manage3MouseClicked

    private void p_manage5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage5MouseClicked
       userform usf= new userform();
       usf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_p_manage5MouseClicked

    private void p_manage5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage5MouseEntered
     p_manage5.setBackground(hovercolor);
    }//GEN-LAST:event_p_manage5MouseEntered

    private void p_manage5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_manage5MouseExited
        p_manage5.setBackground(navcolor);
    }//GEN-LAST:event_p_manage5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminname;
    public javax.swing.JLabel adminname1;
    public javax.swing.JLabel adminname2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel p_manage;
    private javax.swing.JPanel p_manage2;
    private javax.swing.JPanel p_manage3;
    private javax.swing.JPanel p_manage4;
    private javax.swing.JPanel p_manage5;
    // End of variables declaration//GEN-END:variables
}
