/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class applyscholarship extends javax.swing.JFrame {

    /**
     * Creates new form applyscholarship
     */
    public applyscholarship() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        scholarshipname = new javax.swing.JTextField();
        studid = new javax.swing.JComboBox<>();
        course = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        scholarshipdes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        schid = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        scholtype = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        genders = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Student ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 77, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 52, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Scholarship ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 300, 105, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Scholarship Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 360, 130, 17);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(270, 100, 151, 27);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 80, 49, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Course:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 130, 55, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Contact:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 180, 58, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Scholarship Description:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 300, 172, 20);

        ADD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD);
        ADD.setBounds(290, 450, 71, 40);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 450, 79, 40);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(10, 150, 160, 27);

        scholarshipname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholarshipnameActionPerformed(evt);
            }
        });
        jPanel1.add(scholarshipname);
        scholarshipname.setBounds(10, 380, 160, 27);

        studid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidActionPerformed(evt);
            }
        });
        jPanel1.add(studid);
        studid.setBounds(10, 100, 162, 27);

        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        jPanel1.add(course);
        course.setBounds(270, 150, 151, 27);

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel1.add(contact);
        contact.setBounds(10, 200, 151, 27);

        scholarshipdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholarshipdesActionPerformed(evt);
            }
        });
        jPanel1.add(scholarshipdes);
        scholarshipdes.setBounds(270, 320, 151, 100);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("SCHOLARSHIP APPLICATION FORM ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 25, 427, 29);

        schid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schidActionPerformed(evt);
            }
        });
        jPanel1.add(schid);
        schid.setBounds(10, 320, 160, 27);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Scholarship Type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 420, 124, 17);

        scholtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholtypeActionPerformed(evt);
            }
        });
        jPanel1.add(scholtype);
        scholtype.setBounds(10, 440, 160, 27);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Name:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 130, 52, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Gender:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 240, 130, 17);

        genders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendersActionPerformed(evt);
            }
        });
        jPanel1.add(genders);
        genders.setBounds(10, 260, 160, 27);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Status:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(270, 190, 48, 17);

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(270, 210, 151, 27);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scholarship.jpg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 490, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scholarshipnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scholarshipnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scholarshipnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void scholarshipdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scholarshipdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scholarshipdesActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       application uf= new application();
      uf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            dbConnector connect = new dbConnector();
            ResultSet rs = connect.getData("SELECT * FROM tbl_student");
            ResultSet res = connect.getData("SELECT * FROM tbl_scholarship");
            while(rs.next()){
                studid.addItem(rs.getString("student_id"));
            }
            while(res.next()){
                schid.addItem(res.getString("scholarship_id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(applyscholarship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void scholtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scholtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scholtypeActionPerformed

    private void gendersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendersActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void studidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidActionPerformed
dbConnector dbc = new dbConnector();
        try {
            ResultSet res = dbc.getData("SELECT * FROM tbl_student WHERE student_id = '"+studid.getSelectedItem()+"'");
            while(res.next()){
                fname.setText(res.getString("student_name"));
                contact.setText(res.getString("student_contact"));
                email.setText(res.getString("student_email"));
                genders.setText(res.getString("gender"));
                course.setText(res.getString("student_course"));
                status.setText(res.getString("status"));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(applyscholarship.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_studidActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void schidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schidActionPerformed
      dbConnector dbc = new dbConnector();
        try {
            ResultSet res = dbc.getData("SELECT * FROM tbl_scholarship WHERE scholarship_id = '"+schid.getSelectedItem()+"'");
            while(res.next()){
              scholarshipname.setText(res.getString("scholarship_name"));
              scholtype.setText(res.getString("scholarship_type"));
                scholarshipdes.setText(res.getString("scholarship_description"));
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(applyscholarship.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_schidActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
         dbConnector dbc = new dbConnector();
        {
            dbc.insertData("INSERT INTO tbl_application (student_id,scholarship_id,status) VALUES ("+ studid.getSelectedItem() + ","+ schid.getSelectedItem() + ",'Available')");
            
            
        }       
        application usf = new application();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applyscholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applyscholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applyscholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applyscholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applyscholarship().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    public javax.swing.JTextField contact;
    public javax.swing.JTextField course;
    public javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    public javax.swing.JTextField genders;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> schid;
    public javax.swing.JTextField scholarshipdes;
    public javax.swing.JTextField scholarshipname;
    public javax.swing.JTextField scholtype;
    public javax.swing.JTextField status;
    public javax.swing.JComboBox<String> studid;
    // End of variables declaration//GEN-END:variables
}
