/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import config.session;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import user.userDetails;

/**
 *
 * @author SCC
 */
public class userform extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public userform() {
        initComponents();
        displayData();
        
    }
     Color navcolor = new Color(51,204,255);
     Color hovercolor = new Color (255,204,255);
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT u_id,u_fname,u_lname,u_email,u_type,u_status,u_image FROM tbl_user");
          usertable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        currentuser = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        p_add = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        p_edit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p_delete = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        userstable = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        manageuser2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setText("Users Form");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 260, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-student-100.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 0, 100, 80);

        currentuser.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        currentuser.setText("Current User");
        jPanel1.add(currentuser);
        currentuser.setBounds(570, 70, 90, 20);

        userid.setText("User ID");
        jPanel1.add(userid);
        userid.setBounds(580, 100, 36, 14);

        p_add.setBackground(new java.awt.Color(51, 204, 255));
        p_add.setMinimumSize(new java.awt.Dimension(110, 30));
        p_add.setPreferredSize(new java.awt.Dimension(110, 30));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("ADD");
        p_add.add(jLabel5);
        jLabel5.setBounds(30, 10, 30, 17);

        jPanel1.add(p_add);
        p_add.setBounds(40, 60, 90, 30);

        p_edit.setBackground(new java.awt.Color(51, 204, 255));
        p_edit.setMinimumSize(new java.awt.Dimension(110, 30));
        p_edit.setPreferredSize(new java.awt.Dimension(110, 30));
        p_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_editMouseExited(evt);
            }
        });
        p_edit.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setText("EDIT");
        p_edit.add(jLabel3);
        jLabel3.setBounds(20, 10, 31, 17);

        jPanel1.add(p_edit);
        p_edit.setBounds(40, 100, 90, 30);

        p_delete.setBackground(new java.awt.Color(51, 204, 255));
        p_delete.setMinimumSize(new java.awt.Dimension(110, 30));
        p_delete.setPreferredSize(new java.awt.Dimension(110, 30));
        p_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_deleteMouseExited(evt);
            }
        });
        p_delete.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("DELETE");
        p_delete.add(jLabel9);
        jLabel9.setBounds(20, 7, 60, 20);

        jPanel1.add(p_delete);
        p_delete.setBounds(40, 140, 90, 30);

        userstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userstableMouseClicked(evt);
            }
        });

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        usertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertableMouseClicked(evt);
            }
        });
        userstable.setViewportView(usertable);

        jPanel1.add(userstable);
        userstable.setBounds(10, 180, 730, 221);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 420, 90, 27);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 420, 90, 27);

        manageuser2.setBackground(new java.awt.Color(51, 204, 255));
        manageuser2.setPreferredSize(new java.awt.Dimension(170, 180));
        manageuser2.setRequestFocusEnabled(false);
        manageuser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageuser2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageuser2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageuser2MouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-admin-100.png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("My Information");

        javax.swing.GroupLayout manageuser2Layout = new javax.swing.GroupLayout(manageuser2);
        manageuser2.setLayout(manageuser2Layout);
        manageuser2Layout.setHorizontalGroup(
            manageuser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageuser2Layout.createSequentialGroup()
                .addGroup(manageuser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageuser2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageuser2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageuser2Layout.setVerticalGroup(
            manageuser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageuser2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(manageuser2);
        manageuser2.setBounds(550, 120, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scholarship.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userstableMouseClicked
   
    }//GEN-LAST:event_userstableMouseClicked

    private void usertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertableMouseClicked
     
    }//GEN-LAST:event_usertableMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       session sess = session.getInstance();
       userid.setText(""+sess.getUid());
        
    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
       
     p_add.setBackground(hovercolor);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
       
     p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void p_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseEntered
       p_edit.setBackground(hovercolor);
    }//GEN-LAST:event_p_editMouseEntered

    private void p_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseExited
        p_edit.setBackground(navcolor);
    }//GEN-LAST:event_p_editMouseExited

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
       createuserform cuf = new createuserform();
       cuf.setVisible(true);
       cuf.remove.setEnabled(false);
       cuf.select.setEnabled(true);
       this.dispose();
    }//GEN-LAST:event_p_addMouseClicked

    private void p_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseClicked
        int rowIndex = usertable.getSelectedRow();
       
       if(rowIndex<0){
           JOptionPane.showMessageDialog(null,"Please Select some Item");
       }else{
           
            
           try{
               dbConnector dbc = new dbConnector();
               TableModel tbl = usertable.getModel();
               ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '"+tbl.getValueAt(rowIndex,0)+"'");
            if(rs.next()){
                createuserform cuf = new createuserform();
                cuf.uid.setText(""+rs.getInt("u_id"));
                cuf.fname.setText(""+rs.getString("u_fname"));
                cuf.lname.setText(""+rs.getString("u_lname"));
                cuf.email.setText(""+rs.getString("u_email"));
                cuf.username.setText(""+rs.getString("u_username"));
                cuf.password.setText(""+rs.getString("u_password"));
                cuf.usertype.setSelectedItem(""+rs.getString("u_type"));
                cuf.us.setSelectedItem(""+rs.getString("u_status"));
                cuf.image.setIcon(cuf.ResizeImage(rs.getString("u_image"),null, cuf.image));
                cuf.oldpath = rs.getString("u_image");
                cuf.path = rs.getString("u_image");
                cuf.destination = rs.getString("u_image");
                cuf.ADD.setEnabled(false); 
                cuf.UPDATE.setEnabled(true);
                cuf.setVisible(true);
                this.dispose();
                
             if(rs.getString("u_image").isEmpty()){
                 cuf.select.setEnabled(true);
                 cuf.remove.setEnabled(false);
             }else{
                 cuf.select.setEnabled(false);
                 cuf.remove.setEnabled(true);
             }   
          
            }
           }catch(SQLException ex){
               System.out.println(""+ex);
           }
       } 
      
    }//GEN-LAST:event_p_editMouseClicked

    private void p_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseClicked
 
    }//GEN-LAST:event_p_deleteMouseClicked

    private void p_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseEntered
     p_delete.setBackground(hovercolor);       
    }//GEN-LAST:event_p_deleteMouseEntered

    private void p_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_deleteMouseExited
        p_delete.setBackground(navcolor);
    }//GEN-LAST:event_p_deleteMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     admindashboard ds = new admindashboard ();
        ds.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowIndex = usertable.getSelectedRow();
       
       if(rowIndex<0){
           JOptionPane.showMessageDialog(null,"Please Select some Item");
       }else{
           
            
           try{
               dbConnector dbc = new dbConnector();
               TableModel tbl = usertable.getModel();
               ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_id = '"+tbl.getValueAt(rowIndex,0)+"'");
            if(rs.next()){
                printform pf = new printform();
                pf.studid.setText(""+rs.getInt("u_id"));
                pf.fname.setText(""+rs.getString("u_fname"));
                pf.scholarname.setText(""+rs.getString("u_lname"));
                pf.scholarid.setText(""+rs.getString("u_email"));
                pf.type.setText(""+rs.getString("u_username"));
                pf.status.setText(""+rs.getString("u_type"));
                pf.des.setText(""+rs.getString("u_status"));
            
                pf.setVisible(true);
                this.dispose();
         
         
                this.dispose();
                
          
          
            }
           }catch(SQLException ex){
               System.out.println(""+ex);
           }
       } 
      
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void manageuser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuser2MouseClicked
        userDetails ud = new userDetails();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageuser2MouseClicked

    private void manageuser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuser2MouseEntered

    }//GEN-LAST:event_manageuser2MouseEntered

    private void manageuser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuser2MouseExited

    }//GEN-LAST:event_manageuser2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel currentuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel manageuser2;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel p_delete;
    private javax.swing.JPanel p_edit;
    public javax.swing.JLabel userid;
    private javax.swing.JScrollPane userstable;
    public javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
